spring.application.name=notification-service


server.port = 9040
server.servlet.context-path=/notification

#DB Connections
spring.datasource.url=jdbc:postgresql://localhost:5432/notificationDB
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=postgres
spring.datasource.password=1001
spring.jpa.defer-datasource-initialization=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.web=DEBUG


# ------ EUREKA Connection --------

eureka.client.service-url.defaultZone= http://localhost:8761/eureka