
server:
  port: 8080

eureka.client.service-url.defaultZone: http://localhost:8761/eureka


jwt:
  secretKey: dfvsdbadcwq3rf3gethrw5htrn#$%QFwe3dfggd9908yfgndfzszsvthtnssdfsdfrt34the24t



spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: ${USER_SERVICE_URI:lb://USER-SERVICE}
              predicates:
                - Path=/api/v1/users/**
              filters:
                - StripPrefix=2

            - id: post-service
              uri: ${POSTS_SERVICE_URI:lb://POST-SERVICE}
              predicates:
                - Path=/api/v1/posts/**
              filters:
                - StripPrefix=2
                - name: AuthenticationFilter

            - id: connection-service
              uri: ${CONNECTIONS_SERVICE_URI:lb://CONNECTION-SERVICE}
              predicates:
                - Path=/api/v1/connections/**
              filters:
                - StripPrefix=2
                - name: AuthenticationFilter