spring.application.name=postService
server.servlet.context-path=/api/v1/posts
server.port = 9010


#DB Connections
spring.datasource.url=jdbc:postgresql://localhost:5432/postDB
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=postgres
spring.datasource.password=1001
spring.jpa.defer-datasource-initialization=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.web=DEBUG